services:
  test-db:
    image: postgres:16
    container_name: test-db
    ports:
      - "9000:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: test_db